CREATE TABLE IF NOT EXISTS public.bullish_signals_monitoring
(
    id integer NOT NULL DEFAULT nextval('bullish_signals_check_id_seq'::regclass),
    symbol text COLLATE pg_catalog."default",
    timeframe text COLLATE pg_catalog."default",
    current_price numeric,
    score numeric,
    rsi numeric,
    atr numeric,
    macd_histogram numeric,
    golden_cross boolean,
    bullish_engulfing boolean,
    hammer boolean,
    close_to_support boolean,
    morning_star boolean,
    three_white_soldiers boolean,
    doji boolean,
    increasing_volume boolean,
    volume_spike boolean,
    macd_crossover boolean,
    price_above_ma50 boolean,
    price_above_ma200 boolean,
    rsi_bullish_divergence boolean,
    falling_wedge_breakout boolean,
    alert_triggered_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    condition_set integer,
    notification integer DEFAULT 0
)
